<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true"
    CodeBehind="StationeryRequest.aspx.cs" Inherits="SA33.Team12.SSIS.Test.StationeryRequest" %>

<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
    <h1>
        Stationery Request Form</h1>
    <table>
        <tr>
            <td>
                <asp:DropDownList ID="CategoryDDL" runat="server" AutoPostBack="True" OnSelectedIndexChanged="CategoryDDL_SelectedIndexChanged">
                    <asp:ListItem>--Select Category--</asp:ListItem>
                </asp:DropDownList>
                <asp:ObjectDataSource ID="CategoryDS" runat="server" SelectMethod="GetAllCategories"
                    TypeName="SA33.Team12.SSIS.BLL.CatalogManager"></asp:ObjectDataSource>
            </td>
            <td>
                <asp:DropDownList ID="StationeryDDL" runat="server" AutoPostBack="True">
                    <asp:ListItem>--Select Item--</asp:ListItem>
                </asp:DropDownList>
                <asp:ObjectDataSource ID="StationeryDS" runat="server" SelectMethod="GetStationeriesByCategory"
                    TypeName="SA33.Team12.SSIS.BLL.CatalogManager">
                    <SelectParameters>
                        <asp:ControlParameter ControlID="CategoryDDL" Name="CategoryID" PropertyName="SelectedValue"
                            Type="Int32" />
                    </SelectParameters>
                </asp:ObjectDataSource>
            </td>
            <td>
                <asp:TextBox ID="QuantityNeededTextBox" runat="server">Quantity Needed</asp:TextBox>
            </td>
            <td>
                <asp:Button ID="AddItemButton" runat="server" Text="Add" 
                    OnClick="AddItemButton_Click" />
            </td>
        </tr>
    </table>
    <asp:GridView ID="RequisitionItemGridView" runat="server" AutoGenerateColumns="False"
        AutoGenerateEditButton="True" 
        OnRowEditing="RequisitionItemGridView_RowEditing" 
        onrowupdating="RequisitionItemGridView_RowUpdating" 
        AutoGenerateDeleteButton="True" ondatabound="RequisitionItemGridView_DataBound" 
        onrowdeleting="RequisitionItemGridView_RowDeleting">
        <Columns>
            <asp:TemplateField HeaderText="StationeryID">
                <EditItemTemplate>
                    <asp:TextBox ID="StationeryIDTextBox" runat="server" 
                        Text='<%# Bind("StationeryID") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="StationeryIDLabel" runat="server" Text='<%# Eval("StationeryID") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Quantity Needed">
                <EditItemTemplate>
                    <asp:TextBox ID="QuantityRequestedTextBox" runat="server" 
                        Text='<%# Bind("QuantityRequested") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="QuantityRequestedLabel" runat="server" Text='<%# Eval("QuantityRequested") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
        </Columns>
    </asp:GridView>
    <table>
        <tr>
            <td>
                <asp:DropDownList ID="DropDownList1" runat="server">
                </asp:DropDownList>
            </td>
            <td>
                <asp:TextBox ID="StationeryDescriptionTextBox" runat="server" 
                    TextMode="MultiLine">Description</asp:TextBox>
            </td>
            <td>
                <asp:TextBox ID="ReasonTextBox" runat="server" TextMode="MultiLine">Reason</asp:TextBox>
            </td>
            <td>
                <asp:TextBox ID="SpecialQuantityRequestedTextBox" runat="server"></asp:TextBox>
            </td>
            <td>
                <asp:TextBox ID="UOMTextBox" runat="server"></asp:TextBox>
            </td>
            <td>
                <asp:Button ID="AddSpecialItemButton" runat="server" Text="Add" 
                    onclick="AddSpecialItemButton_Click" />
            </td>
        </tr>
    </table>
    <asp:GridView ID="SpecialRequisitionItemGridView" runat="server" 
        AutoGenerateColumns="False">
        <Columns>
            <asp:BoundField DataField="Name" HeaderText="Item Name" />
            <asp:BoundField DataField="Description" HeaderText="Item Description" />
            <asp:BoundField DataField="RemarkByRequester" HeaderText="Reason" />
            <asp:BoundField DataField="QuantityRequested" HeaderText="Quantity Needed" />
        </Columns>
    </asp:GridView>
    <br />
    <asp:Button ID="SubmitButton" runat="server" onclick="SubmitButton_Click" 
        Text="Submit Request" />
</asp:Content>
